services:
  - type: web
    name: restaurant-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-db
          property: connectionString

databases:
  - name: restaurant-db
    databaseName: restaurant_reservation_db
    user: restaurant_user
